### ISSUE TITLE
Set-Up

### ISSUE THREAD

**Issue by PigeonCarbon** [nuxshed/dotfiles#7]
hi :) keep getting this error https://imgur.com/8BJibcG.png , cloned bling into ~/.config/awesome/modules but says im missing some stuff :/ any help appreciated :)

**Comment by wiredmatt** [comment]
If you see the [.gitignore](https://github.com/nuxshed/dotfiles/blob/main/.gitignore), the `modules` directory is ignored (not sure why).

```bash
mkdir ~/.config/awesome/modules
cd ~/.config/awesome/modules
git clone git@github.com:BlingCorp/bling.git # or use https if you prefer
```

That should fix the warning about Bling missing, but I think @nuxshed uses other modules as well.

The best would be to use git modules instead, that's what I'm doing in my [config](https://github.com/system32uwu/dots/tree/main/awesome/mods)

**Comment by PigeonCarbon** [comment]
unfortunately didnt work :/ still a bunch of errors and some even /usr/lib... I'm away from my pc for a few days but any help is still appreciated :) i love the look of these dots a lot :D

**Comment by wiredmatt** [comment]
Yeah, that solution was to fix Bling missing, what is the other error that you're getting now? I kinda merged some of what the OP made into my own rice, I didn't fully clone it so I don't know what the errors you're getting might be

**Comment by PigeonCarbon** [comment]
Yeah, similar to my last screenshot apart from some of the awesome/modules errors are missing, most now are /usr/lib or /usr/...., Can't remember the exact ones and won't be home until Sunday, but they should all be in the before screenshot :)

**Comment by wiredmatt** [comment]
I think you might be using the stable awesomewm package then. Check if you're using awesome or awesome-git, it should be the [later](https://aur.archlinux.org/packages/awesome-git). 

It tells you it's missing stuff in /usr/lib because awesome and lua try to search under a given set of directories for the modules you are trying to import, if you've everything right in your .config/awesome it should pick them up from there. It seems to me that you are missing other modules besides bling.

**Comment by PigeonCarbon** [comment]
I'll get back to you about it :) I think it is awesome-git but I'm super new to Linux so could be easily wrong, but like I said I can confirm this once I'm back :)

**Comment by PigeonCarbon** [comment]
@system32uwu hi :) got home and checked, I'm on awesome-git. https://imgur.com/sp0YlP6.png is the current errors and https://imgur.com/kdK1MZj.png is my current config, just so we can make sure it doesn't look like I'm missing anything vital. Thanks for the help :)
edit: saw most of the errors involving "rubato" and realised i didnt have it installed, installed it but still the same errors
Edit2: removed "require rubato" since I realised it's just a lil animation software which I could live without from ~/.config/awesome/ui/action.lua and the errors are gone, but I boot into the standard awesome terminal

**Comment by wiredmatt** [comment]
You installed rubato by moving into ~/.config/awesome/modules, and running `git clone https://github.com/andOrlando/rubato.git` right? Instead of require "rubato" it should probably be require "modules.rubato" as well.

What do you mean by standard awesome terminal though? This? 
![image](https://user-images.githubusercontent.com/29718978/172063245-84df4245-4e17-4aaa-9a33-afa38f060409.png)

Lastly, it could also be the case that you're missing the packages that are being spawned somewhere in the config. Are you using nixOS as PigeonCarbon is?

**Comment by PigeonCarbon** [comment]
Hi, yeah that's the screen, although I realised that there is an autostart script in ~/.config/herbstlufwm/autostart.sh so I disabled my awesome autostart and let that kick in instead (slight oversight by me). I was booted into root terminal and tried running the autostart again and got a tint2 error; "using glib slice allocator (default). Run tint2 with environment variable G_SLICE=always-malloc in case of strange behaviour or crasher
Tint2: could not open display!

I get booted into root but can't start the wm since I'm in root lol, bit of a loop I'm not sure how to get out of.
Also, I use arch, btw :)

**Comment by wiredmatt** [comment]
So you're missing [tint2](https://wiki.archlinux.org/title/tint2#Installation)

`su - yourUsername #(to log in as your regular user)`

**Comment by PigeonCarbon** [comment]
https://imgur.com/XQSvaQH.png thats the weird part, i do have it installed :thinking: i think since im launched into root, when i run autostart is cant display all the things in a terminal, i need to be in some sort of WM and that explains the error, but as soon as i reboot im launched into the root with no window manager so im very confused

**Comment by wiredmatt** [comment]
Just login as your user instead:
```bash
$ su - mocha
```

then just start awesome:

```bash
$ awesome
```

you can also install [lightdm](https://wiki.archlinux.org/title/LightDM#Installation) or sddm to select your user and the WM / DE with a gui.

**Comment by PigeonCarbon** [comment]
I use lightdm already, and after running that command I get: awesome: main694: cannot open display (error 5)
I can launch into the normal awesome using lightdm, just like the screenshot you shown above, but not the dotfiles that are on this git :/

**Comment by PigeonCarbon** [comment]
after some tweaking i got an error message, https://imgur.com/QTfkP5r.png , hope this helps but i dont know what to do from here. 
- again, im only a week into linux so i dont know much, sorry for the bother :)

**Comment by wiredmatt** [comment]
Yeah, that's because xorg is not running in a TTY environment (where you're currently at). The autostart script that you see there is for herbsluftwm (another TWM), not for awesome. Awesome itself should launch when you launch awesome from lightdm. From the error message you got from tint2, I think you might be missing some deps on base and base-devel. Anyways you can disable where tint2 is invoked and see if it boots into awesome properly. From there on, try to read from the tint2 wiki, you can start [here](https://gitlab.com/o9000/tint2/-/wikis/Install#dependencies), check if you have those dependencies installed in your system. You can do so by running:

```bash
sudo pacman -Qee | grep packageName
```

Lastly, this dotfiles are meant to be used in a nixOS machine, if you want to use them so badly you can just install nix, which is way cleaner than arch (I also use arch because it's a rolling release but if you want something actually usable you should choose something better, like nix)
